# Generated by Django 4.0.3 on 2022-03-27 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateField()),
                ("end", models.DateField(blank=True, null=True)),
                (
                    "mtype",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Regular"),
                            (1, "Discounted"),
                            (2, "Free"),
                            (3, "Remote"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "real_name",
                    models.CharField(max_length=255, verbose_name="Real name"),
                ),
                (
                    "address_street1",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Street Address"
                    ),
                ),
                (
                    "address_street2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Street Address 2"
                    ),
                ),
                (
                    "address_street3",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Street Address 3"
                    ),
                ),
                (
                    "address_locality",
                    models.CharField(blank=True, max_length=255, verbose_name="Town"),
                ),
                (
                    "address_state",
                    models.CharField(blank=True, max_length=255, verbose_name="County"),
                ),
                (
                    "address_postalcode",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Postcode"
                    ),
                ),
                (
                    "address_country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                (
                    "xero_uuid",
                    models.UUIDField(blank=True, null=True, verbose_name="Xero UUID"),
                ),
                (
                    "membership_number",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("membership_suspended", models.BooleanField(default=False)),
                (
                    "membership_status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Non-member"),
                            (1, "Applicant"),
                            (2, "Approved"),
                            (3, "Member"),
                            (4, "Suspended"),
                            (5, "Leaving"),
                            (6, "Alumni"),
                        ],
                        default=0,
                        editable=False,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="These notes are visible to the user."
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [("view_register", "Can view the register of members")],
            },
        ),
        migrations.CreateModel(
            name="MembershipSponsor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "sponsee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("sponsor", "sponsee")},
            },
        ),
    ]
