# Generated by Django 4.0.3 on 2022-04-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0002_alter_member_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="display_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="member",
            name="real_name",
            field=models.CharField(max_length=255),
        ),
    ]
