# Generated by Django 4.0.3 on 2022-04-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0003_member_display_name_alter_member_real_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="privacy",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Low - Public"),
                    (1, "Medium - Members Only"),
                    (2, "Paranoid - Trust No One"),
                ],
                default=1,
            ),
        ),
    ]
