# Generated by Django 5.1.3 on 2024-11-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0004_member_privacy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipterm",
            name="mtype",
            field=models.SmallIntegerField(
                choices=[
                    (4, "Regular"),
                    (0, "Regular (minimum £25)"),
                    (1, "Discounted"),
                    (2, "Free"),
                    (3, "Remote"),
                ],
                default=0,
            ),
        ),
    ]
