# Generated by Django 4.2.7 on 2023-11-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groupadmin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupproperties",
            name="owners_manage_owners",
            field=models.BooleanField(default=False),
        ),
    ]
