# Generated by Django 4.0.4 on 2024-06-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groupadmin", "0002_groupproperties_owners_manage_owners"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupproperties",
            name="advertise_owners",
            field=models.BooleanField(default=False),
        ),
    ]
