# Generated by Django 4.0.3 on 2022-03-03 11:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NFCToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid hexadecimal value",
                                regex="^\\s*[0-9a-fA-F]+\\s*$",
                            )
                        ],
                        verbose_name="UID",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "last_seen",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "last_location",
                    models.CharField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nfctokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("auth_token", "Can authenticate a token"),
                    ("export_tokens", "Can export all tokens"),
                ],
            },
        ),
        migrations.CreateModel(
            name="NFCTokenLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(editable=False)),
                ("location", models.CharField(editable=False, max_length=255)),
                ("uid", models.CharField(editable=False, max_length=32)),
                ("name", models.CharField(blank=True, editable=False, max_length=255)),
                (
                    "token_description",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "authorized",
                    models.BooleanField(blank=True, editable=False, null=True),
                ),
                (
                    "ltype",
                    models.CharField(
                        default="unknown",
                        editable=False,
                        max_length=32,
                        verbose_name="Type",
                    ),
                ),
                (
                    "token",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="nfctokens.nfctoken",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nfctokenlogs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
