# Generated by Django 4.0.3 on 2022-04-02 17:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nfctokens", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nfctoken",
            name="uid",
            field=models.CharField(
                max_length=32,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid UID, either 8 or 14 hexadecimal digits",
                        regex="^\\s*([0-9a-fA-F]{8}|[0-9a-fA-F]{14})\\s*$",
                    )
                ],
                verbose_name="UID",
            ),
        ),
        migrations.AlterField(
            model_name="nfctoken",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nfctokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
