# Generated by Django 4.0.3 on 2022-04-06 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nfctokens", "0002_alter_nfctoken_uid_alter_nfctoken_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nfctoken",
            name="uid",
            field=models.CharField(
                max_length=32,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid UID, either 8 or 14 hexadecimal digits",
                        regex="^\\s*([0-9a-fA-F]{8}|[0-9a-fA-F]{14})\\s*$",
                    ),
                    django.core.validators.RegexValidator(
                        inverse_match=True,
                        message="This is a randomly-generated UID which cannot be used for authentication",
                        regex="^\\s*08[0-9a-fA-F]{6}\\s*$",
                    ),
                ],
                verbose_name="UID",
            ),
        ),
    ]
