# Generated by Django 4.0.3 on 2022-04-06 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nfctokens", "0003_alter_nfctoken_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nfctoken",
            name="uid",
            field=models.CharField(
                max_length=32,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid UID of 8, 14 or 20 hexadecimal digits",
                        regex="^\\s*([0-9a-fA-F]{8}|[0-9a-fA-F]{14}|[0-9a-fA-F]{20})\\s*$",
                    ),
                    django.core.validators.RegexValidator(
                        inverse_match=True,
                        message="This is a randomly-generated UID which cannot be used for authentication",
                        regex="^\\s*08[0-9a-fA-F]{6}\\s*$",
                    ),
                ],
                verbose_name="UID",
            ),
        ),
    ]
