# Generated by Django 4.0.4 on 2022-04-15 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nfctokens", "0005_nfctokenlog_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nfctoken",
            options={
                "permissions": [
                    ("auth_token", "Can authenticate a token"),
                    ("export_tokens", "Can export all tokens"),
                ],
                "verbose_name": "NFC Token",
            },
        ),
        migrations.AlterModelOptions(
            name="nfctokenlog",
            options={"verbose_name": "NFC Token Log"},
        ),
    ]
