# Generated by Django 4.0.4 on 2022-04-21 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nfctokens", "0006_alter_nfctoken_options_alter_nfctokenlog_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nfctoken",
            options={
                "permissions": [
                    ("auth_token", "Can authenticate a token"),
                    ("export_tokens", "Can export all tokens"),
                    ("self_configure_token", "Can configure own NFC Token"),
                ],
                "verbose_name": "NFC Token",
            },
        ),
        migrations.AlterModelOptions(
            name="nfctokenlog",
            options={
                "permissions": [("self_view_tokenlog", "Can view own NFC Token Log")],
                "verbose_name": "NFC Token Log",
            },
        ),
    ]
