# Generated by Django 4.0.4 on 2022-04-24 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("nfctokens", "0007_alter_nfctoken_options_alter_nfctokenlog_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="nfctoken",
            name="last_edit",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
