# Generated by Django 4.1.6 on 2023-02-05 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nfctokens", "0008_nfctoken_last_edit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nfctoken",
            options={
                "permissions": [
                    ("auth_token", "Can authenticate a token"),
                    ("auth_token_name", "Can see name during authentication"),
                    ("auth_token_email", "Can see email during authentication"),
                    ("auth_token_groups", "Can see groups during authentication"),
                    ("export_tokens", "Can export all tokens"),
                    ("self_configure_token", "Can configure own NFC Token"),
                ],
                "verbose_name": "NFC Token",
            },
        ),
    ]
