# Generated by Django 4.0.3 on 2022-03-26 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("info", models.TextField(blank=True)),
                ("advertised", models.BooleanField()),
                (
                    "subscribe_policy",
                    models.SmallIntegerField(
                        choices=[
                            (0, "None"),
                            (1, "Confirm"),
                            (2, "Require approval"),
                            (3, "Confirm and approve"),
                        ]
                    ),
                ),
                ("archive_private", models.BooleanField()),
                ("subscribe_auto_approval", models.TextField(blank=True)),
                (
                    "auto_unsubscribe",
                    models.BooleanField(
                        default=False,
                        help_text="Should non-group members be automatically unsubscribed?",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("audit_list", "Can audit the subscribers of a mailing list")
                ],
            },
        ),
        migrations.CreateModel(
            name="ChangeOfAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("old_email", models.EmailField(max_length=254)),
                ("new_email", models.EmailField(max_length=254)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Changes of address",
            },
        ),
        migrations.CreateModel(
            name="GroupPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Allow"),
                            (1, "Recommend"),
                            (2, "Prompt"),
                            (3, "Force"),
                        ],
                        default=0,
                    ),
                ),
                ("prompt", models.TextField(blank=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailinglist_policies",
                        to="auth.group",
                    ),
                ),
                (
                    "mailing_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_policies",
                        to="mailman2.mailinglist",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Group policies",
                "unique_together": {("mailing_list", "group")},
            },
        ),
    ]
