# Generated by Django 4.2.13 on 2024-06-07 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apikeys", "0002_alter_apikey_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
