# Generated by Django 4.2.13 on 2024-06-07 13:23

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    ApiKey = apps.get_model("apikeys", "ApiKey")
    for row in ApiKey.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("apikeys", "0003_apikey_uuid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
